#!/bin/bash


_python_() {
    python3${pVer%.*} -c "$1"
}

_FLAMINGBOT_MAIN() {
    $(_python_ 'from git import Repo
import sys
_UPSTREAM_ = "https://github.com/ITS-FLAMINGBOT/FLAMINGBOT"
_BRANCH_ = "master"
repo = Repo.init()
origin = repo.create_remote("temponame", _UPSTREAM_)
origin.fetch()
repo.create_head(_BRANCH_, origin.refs[_BRANCH_])
repo.heads[_BRANCH_].checkout(True) ')
}

_flaming_repo () {
    local hrepo
    hrepo=`echo "aHR0cHM6Ly9naXRodWIuY29tL0ZMQU1JTkctT1MvRkxBTUlOR1VTRVJCT1Q=" | base64 -d`
    echo "$rlink"
}

_flaming_zip () {
    echo "aHR0cHM6Ly9naXRodWIuY29tL0ZMQU1JTkctT1MvRkxBTUlOR1VTRVJCT1QvYXJjaGl2ZS9tYXN0ZXIuemlw" | base64 -d
}

_FLAMINGBOT_PLUG() {
    local hrepo=$(_flaming_repo)
    $(_python_ 'from git import Repo
import sys
_UPSTREAM_ = "'$hrepo'"
_BRANCH_ = "master"
repo = Repo.init()
origin = repo.create_remote("temponame", _UPSTREAM_)
origin.fetch()
repo.create_head(_BRANCH_, origin.refs[_BRANCH_])
repo.heads[_BRANCH_].checkout(True) ')
}

_starter () {
    local flamingpath
    hellpath="FLAMINGUSERBOT.zip"
    echo "••• DOWNLOADING FLAMINGBOT •••"
    wget -q $(_flaming_zip) -O "$flamingpath"
    FLAMINGPATH=$(zipinfo -1 "$flamingpath" | grep -v "/.");
    unzip -qq "$flamingpath"
    rm -rf "$hellpath"
    # _FLAMINGBOT_MAIN
    cd $FLAMINGPATH
    # _FLAMINGBOT_FLAMINGUSERBOT
    python3 ../setup/updater.py ../requirements.txt requirements.txt
    echo "••• STARTING FLAMINGBOTBOT •••"
    python3 flamingrun.py
}

_starter
